/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) segway_nonlinear_mpc_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {2, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {8, 1, 1};

/* segway_nonlinear_mpc_expl_vde_adj:(i0[6],i1[6],i2[2],i3[0])->(o0[8]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24;
  a00=0.;
  if (res[0]!=0) res[0][0]=a00;
  a01=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][1]=a01;
  a01=arg[0]? arg[0][2] : 0;
  a02=sin(a01);
  a03=1.1958143999999998e-03;
  a04=-3.2000000000000003e-04;
  a05=5.0000000000000000e-01;
  a06=arg[2]? arg[2][0] : 0;
  a06=(a05*a06);
  a07=arg[2]? arg[2][1] : 0;
  a07=(a05*a07);
  a06=(a06+a07);
  a07=(a04*a06);
  a08=4.6780000000000003e-05;
  a09=arg[0]? arg[0][5] : 0;
  a10=casadi_sq(a09);
  a11=(a08*a10);
  a12=2.;
  a13=(a12*a01);
  a14=sin(a13);
  a15=(a11*a14);
  a07=(a07+a15);
  a15=1.1099200000000000e-04;
  a10=(a15*a10);
  a16=(a10*a14);
  a07=(a07-a16);
  a16=5.9790719999999991e-04;
  a17=arg[0]? arg[0][3] : 0;
  a18=casadi_sq(a17);
  a18=(a16*a18);
  a19=(a18*a02);
  a07=(a07+a19);
  a19=3.3439999999999998e-03;
  a20=(a19*a06);
  a07=(a07-a20);
  a20=1.4663674080000000e-01;
  a21=(a20*a02);
  a07=(a07+a21);
  a21=1.4947679999999998e-02;
  a22=(a21*a06);
  a01=cos(a01);
  a23=(a22*a01);
  a07=(a07-a23);
  a23=6.4000000000000005e-04;
  a06=(a23*a06);
  a07=(a07-a06);
  a06=3.0109600000000005e-04;
  a24=(a03*a01);
  a06=(a06+a24);
  a24=2.6726451839999992e-03;
  a06=(a06+a24);
  a24=2.5600000000000006e-05;
  a06=(a06+a24);
  a07=(a07/a06);
  a07=(a07/a06);
  a24=arg[1]? arg[1][3] : 0;
  a07=(a07*a24);
  a03=(a03*a07);
  a03=(a02*a03);
  a24=(a24/a06);
  a22=(a22*a24);
  a22=(a02*a22);
  a03=(a03+a22);
  a20=(a20*a24);
  a20=(a01*a20);
  a03=(a03+a20);
  a18=(a18*a24);
  a18=(a01*a18);
  a03=(a03+a18);
  a13=cos(a13);
  a10=(a10*a24);
  a10=(a13*a10);
  a10=(a12*a10);
  a03=(a03-a10);
  a11=(a11*a24);
  a13=(a13*a11);
  a12=(a12*a13);
  a03=(a03+a12);
  if (res[0]!=0) res[0][2]=a03;
  a17=(a17+a17);
  a02=(a02*a24);
  a16=(a16*a02);
  a17=(a17*a16);
  a16=arg[1]? arg[1][2] : 0;
  a17=(a17+a16);
  if (res[0]!=0) res[0][3]=a17;
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a09=(a09+a09);
  a14=(a14*a24);
  a15=(a15*a14);
  a15=(a09*a15);
  a00=(a00-a15);
  a08=(a08*a14);
  a09=(a09*a08);
  a00=(a00+a09);
  if (res[0]!=0) res[0][5]=a00;
  a00=-5.;
  a09=arg[1]? arg[1][5] : 0;
  a00=(a00*a09);
  a04=(a04*a24);
  a23=(a23*a24);
  a01=(a01*a24);
  a21=(a21*a01);
  a23=(a23+a21);
  a19=(a19*a24);
  a23=(a23+a19);
  a04=(a04-a23);
  a23=arg[1]? arg[1][1] : 0;
  a04=(a04+a23);
  a05=(a05*a04);
  a00=(a00+a05);
  if (res[0]!=0) res[0][6]=a00;
  a00=5.;
  a00=(a00*a09);
  a00=(a00+a05);
  if (res[0]!=0) res[0][7]=a00;
  return 0;
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int segway_nonlinear_mpc_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int segway_nonlinear_mpc_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real segway_nonlinear_mpc_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* segway_nonlinear_mpc_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* segway_nonlinear_mpc_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* segway_nonlinear_mpc_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* segway_nonlinear_mpc_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
