/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) segway_nonlinear_mpc_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {6, 1, 1};
static const casadi_int casadi_s1[3] = {6, 6, 1};
static const casadi_int casadi_s2[3] = {6, 2, 1};
static const casadi_int casadi_s3[3] = {2, 1, 1};
static const casadi_int casadi_s4[3] = {0, 1, 1};

/* segway_nonlinear_mpc_expl_vde_forw:(i0[6],i1[6x6],i2[6x2],i3[2],i4[0])->(o0[6],o1[6x6],o2[6x2]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[0]? arg[0][1] : 0;
  if (res[0]!=0) res[0][0]=a00;
  a00=5.0000000000000000e-01;
  a01=arg[3]? arg[3][0] : 0;
  a02=(a00*a01);
  a03=arg[3]? arg[3][1] : 0;
  a04=(a00*a03);
  a02=(a02+a04);
  if (res[0]!=0) res[0][1]=a02;
  a04=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][2]=a04;
  a05=-3.2000000000000003e-04;
  a06=(a05*a02);
  a07=4.6780000000000003e-05;
  a08=arg[0]? arg[0][5] : 0;
  a09=casadi_sq(a08);
  a10=(a07*a09);
  a11=2.;
  a12=arg[0]? arg[0][2] : 0;
  a13=(a11*a12);
  a14=sin(a13);
  a15=(a10*a14);
  a06=(a06+a15);
  a15=1.1099200000000000e-04;
  a09=(a15*a09);
  a16=(a09*a14);
  a06=(a06-a16);
  a16=5.9790719999999991e-04;
  a17=casadi_sq(a04);
  a17=(a16*a17);
  a18=sin(a12);
  a19=(a17*a18);
  a06=(a06+a19);
  a19=3.3439999999999998e-03;
  a19=(a19*a02);
  a06=(a06-a19);
  a19=1.4663674080000000e-01;
  a20=(a19*a18);
  a06=(a06+a20);
  a20=1.4947679999999998e-02;
  a20=(a20*a02);
  a12=cos(a12);
  a21=(a20*a12);
  a06=(a06-a21);
  a21=6.4000000000000005e-04;
  a21=(a21*a02);
  a06=(a06-a21);
  a21=3.0109600000000005e-04;
  a02=1.1958143999999998e-03;
  a22=(a02*a12);
  a21=(a21+a22);
  a22=2.6726451839999992e-03;
  a21=(a21+a22);
  a22=2.5600000000000006e-05;
  a21=(a21+a22);
  a06=(a06/a21);
  if (res[0]!=0) res[0][3]=a06;
  if (res[0]!=0) res[0][4]=a08;
  a22=-5.;
  a01=(a22*a01);
  a23=5.;
  a03=(a23*a03);
  a01=(a01+a03);
  if (res[0]!=0) res[0][5]=a01;
  a01=arg[1]? arg[1][1] : 0;
  if (res[1]!=0) res[1][0]=a01;
  a01=0.;
  if (res[1]!=0) res[1][1]=a01;
  a03=arg[1]? arg[1][3] : 0;
  if (res[1]!=0) res[1][2]=a03;
  a08=(a08+a08);
  a24=arg[1]? arg[1][5] : 0;
  a25=(a08*a24);
  a26=(a07*a25);
  a26=(a14*a26);
  a13=cos(a13);
  a27=arg[1]? arg[1][2] : 0;
  a28=(a11*a27);
  a28=(a13*a28);
  a29=(a10*a28);
  a26=(a26+a29);
  a25=(a15*a25);
  a25=(a14*a25);
  a28=(a09*a28);
  a25=(a25+a28);
  a26=(a26-a25);
  a04=(a04+a04);
  a03=(a04*a03);
  a03=(a16*a03);
  a03=(a18*a03);
  a25=(a12*a27);
  a28=(a17*a25);
  a03=(a03+a28);
  a26=(a26+a03);
  a25=(a19*a25);
  a26=(a26+a25);
  a27=(a18*a27);
  a25=(a20*a27);
  a26=(a26+a25);
  a26=(a26/a21);
  a06=(a06/a21);
  a27=(a02*a27);
  a27=(a06*a27);
  a26=(a26+a27);
  if (res[1]!=0) res[1][3]=a26;
  if (res[1]!=0) res[1][4]=a24;
  if (res[1]!=0) res[1][5]=a01;
  a24=arg[1]? arg[1][7] : 0;
  if (res[1]!=0) res[1][6]=a24;
  if (res[1]!=0) res[1][7]=a01;
  a24=arg[1]? arg[1][9] : 0;
  if (res[1]!=0) res[1][8]=a24;
  a26=arg[1]? arg[1][11] : 0;
  a27=(a08*a26);
  a25=(a07*a27);
  a25=(a14*a25);
  a03=arg[1]? arg[1][8] : 0;
  a28=(a11*a03);
  a28=(a13*a28);
  a29=(a10*a28);
  a25=(a25+a29);
  a27=(a15*a27);
  a27=(a14*a27);
  a28=(a09*a28);
  a27=(a27+a28);
  a25=(a25-a27);
  a24=(a04*a24);
  a24=(a16*a24);
  a24=(a18*a24);
  a27=(a12*a03);
  a28=(a17*a27);
  a24=(a24+a28);
  a25=(a25+a24);
  a27=(a19*a27);
  a25=(a25+a27);
  a03=(a18*a03);
  a27=(a20*a03);
  a25=(a25+a27);
  a25=(a25/a21);
  a03=(a02*a03);
  a03=(a06*a03);
  a25=(a25+a03);
  if (res[1]!=0) res[1][9]=a25;
  if (res[1]!=0) res[1][10]=a26;
  if (res[1]!=0) res[1][11]=a01;
  a26=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][12]=a26;
  if (res[1]!=0) res[1][13]=a01;
  a26=arg[1]? arg[1][15] : 0;
  if (res[1]!=0) res[1][14]=a26;
  a25=arg[1]? arg[1][17] : 0;
  a03=(a08*a25);
  a27=(a07*a03);
  a27=(a14*a27);
  a24=arg[1]? arg[1][14] : 0;
  a28=(a11*a24);
  a28=(a13*a28);
  a29=(a10*a28);
  a27=(a27+a29);
  a03=(a15*a03);
  a03=(a14*a03);
  a28=(a09*a28);
  a03=(a03+a28);
  a27=(a27-a03);
  a26=(a04*a26);
  a26=(a16*a26);
  a26=(a18*a26);
  a03=(a12*a24);
  a28=(a17*a03);
  a26=(a26+a28);
  a27=(a27+a26);
  a03=(a19*a03);
  a27=(a27+a03);
  a24=(a18*a24);
  a03=(a20*a24);
  a27=(a27+a03);
  a27=(a27/a21);
  a24=(a02*a24);
  a24=(a06*a24);
  a27=(a27+a24);
  if (res[1]!=0) res[1][15]=a27;
  if (res[1]!=0) res[1][16]=a25;
  if (res[1]!=0) res[1][17]=a01;
  a25=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][18]=a25;
  if (res[1]!=0) res[1][19]=a01;
  a25=arg[1]? arg[1][21] : 0;
  if (res[1]!=0) res[1][20]=a25;
  a27=arg[1]? arg[1][23] : 0;
  a24=(a08*a27);
  a03=(a07*a24);
  a03=(a14*a03);
  a26=arg[1]? arg[1][20] : 0;
  a28=(a11*a26);
  a28=(a13*a28);
  a29=(a10*a28);
  a03=(a03+a29);
  a24=(a15*a24);
  a24=(a14*a24);
  a28=(a09*a28);
  a24=(a24+a28);
  a03=(a03-a24);
  a25=(a04*a25);
  a25=(a16*a25);
  a25=(a18*a25);
  a24=(a12*a26);
  a28=(a17*a24);
  a25=(a25+a28);
  a03=(a03+a25);
  a24=(a19*a24);
  a03=(a03+a24);
  a26=(a18*a26);
  a24=(a20*a26);
  a03=(a03+a24);
  a03=(a03/a21);
  a26=(a02*a26);
  a26=(a06*a26);
  a03=(a03+a26);
  if (res[1]!=0) res[1][21]=a03;
  if (res[1]!=0) res[1][22]=a27;
  if (res[1]!=0) res[1][23]=a01;
  a27=arg[1]? arg[1][25] : 0;
  if (res[1]!=0) res[1][24]=a27;
  if (res[1]!=0) res[1][25]=a01;
  a27=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][26]=a27;
  a03=arg[1]? arg[1][29] : 0;
  a26=(a08*a03);
  a24=(a07*a26);
  a24=(a14*a24);
  a25=arg[1]? arg[1][26] : 0;
  a28=(a11*a25);
  a28=(a13*a28);
  a29=(a10*a28);
  a24=(a24+a29);
  a26=(a15*a26);
  a26=(a14*a26);
  a28=(a09*a28);
  a26=(a26+a28);
  a24=(a24-a26);
  a27=(a04*a27);
  a27=(a16*a27);
  a27=(a18*a27);
  a26=(a12*a25);
  a28=(a17*a26);
  a27=(a27+a28);
  a24=(a24+a27);
  a26=(a19*a26);
  a24=(a24+a26);
  a25=(a18*a25);
  a26=(a20*a25);
  a24=(a24+a26);
  a24=(a24/a21);
  a25=(a02*a25);
  a25=(a06*a25);
  a24=(a24+a25);
  if (res[1]!=0) res[1][27]=a24;
  if (res[1]!=0) res[1][28]=a03;
  if (res[1]!=0) res[1][29]=a01;
  a03=arg[1]? arg[1][31] : 0;
  if (res[1]!=0) res[1][30]=a03;
  if (res[1]!=0) res[1][31]=a01;
  a03=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][32]=a03;
  a24=arg[1]? arg[1][35] : 0;
  a25=(a08*a24);
  a26=(a07*a25);
  a26=(a14*a26);
  a27=arg[1]? arg[1][32] : 0;
  a28=(a11*a27);
  a28=(a13*a28);
  a29=(a10*a28);
  a26=(a26+a29);
  a25=(a15*a25);
  a25=(a14*a25);
  a28=(a09*a28);
  a25=(a25+a28);
  a26=(a26-a25);
  a03=(a04*a03);
  a03=(a16*a03);
  a03=(a18*a03);
  a25=(a12*a27);
  a28=(a17*a25);
  a03=(a03+a28);
  a26=(a26+a03);
  a25=(a19*a25);
  a26=(a26+a25);
  a27=(a18*a27);
  a25=(a20*a27);
  a26=(a26+a25);
  a26=(a26/a21);
  a27=(a02*a27);
  a27=(a06*a27);
  a26=(a26+a27);
  if (res[1]!=0) res[1][33]=a26;
  if (res[1]!=0) res[1][34]=a24;
  if (res[1]!=0) res[1][35]=a01;
  a01=arg[2]? arg[2][1] : 0;
  if (res[2]!=0) res[2][0]=a01;
  if (res[2]!=0) res[2][1]=a00;
  a01=arg[2]? arg[2][3] : 0;
  if (res[2]!=0) res[2][2]=a01;
  a24=-1.8319999999999999e-03;
  a26=7.4738399999999990e-03;
  a26=(a26*a12);
  a24=(a24-a26);
  a24=(a24+a05);
  a24=(a24/a21);
  a05=arg[2]? arg[2][5] : 0;
  a26=(a08*a05);
  a27=(a07*a26);
  a27=(a14*a27);
  a25=arg[2]? arg[2][2] : 0;
  a03=(a11*a25);
  a03=(a13*a03);
  a28=(a10*a03);
  a27=(a27+a28);
  a26=(a15*a26);
  a26=(a14*a26);
  a03=(a09*a03);
  a26=(a26+a03);
  a27=(a27-a26);
  a01=(a04*a01);
  a01=(a16*a01);
  a01=(a18*a01);
  a26=(a12*a25);
  a03=(a17*a26);
  a01=(a01+a03);
  a27=(a27+a01);
  a26=(a19*a26);
  a27=(a27+a26);
  a25=(a18*a25);
  a26=(a20*a25);
  a27=(a27+a26);
  a27=(a27/a21);
  a25=(a02*a25);
  a25=(a06*a25);
  a27=(a27+a25);
  a27=(a24+a27);
  if (res[2]!=0) res[2][3]=a27;
  if (res[2]!=0) res[2][4]=a05;
  if (res[2]!=0) res[2][5]=a22;
  a22=arg[2]? arg[2][7] : 0;
  if (res[2]!=0) res[2][6]=a22;
  if (res[2]!=0) res[2][7]=a00;
  a00=arg[2]? arg[2][9] : 0;
  if (res[2]!=0) res[2][8]=a00;
  a22=arg[2]? arg[2][11] : 0;
  a08=(a08*a22);
  a07=(a07*a08);
  a07=(a14*a07);
  a05=arg[2]? arg[2][8] : 0;
  a11=(a11*a05);
  a13=(a13*a11);
  a10=(a10*a13);
  a07=(a07+a10);
  a15=(a15*a08);
  a14=(a14*a15);
  a09=(a09*a13);
  a14=(a14+a09);
  a07=(a07-a14);
  a04=(a04*a00);
  a16=(a16*a04);
  a16=(a18*a16);
  a12=(a12*a05);
  a17=(a17*a12);
  a16=(a16+a17);
  a07=(a07+a16);
  a19=(a19*a12);
  a07=(a07+a19);
  a18=(a18*a05);
  a20=(a20*a18);
  a07=(a07+a20);
  a07=(a07/a21);
  a02=(a02*a18);
  a06=(a06*a02);
  a07=(a07+a06);
  a24=(a24+a07);
  if (res[2]!=0) res[2][9]=a24;
  if (res[2]!=0) res[2][10]=a22;
  if (res[2]!=0) res[2][11]=a23;
  return 0;
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void segway_nonlinear_mpc_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int segway_nonlinear_mpc_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int segway_nonlinear_mpc_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real segway_nonlinear_mpc_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* segway_nonlinear_mpc_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* segway_nonlinear_mpc_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* segway_nonlinear_mpc_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* segway_nonlinear_mpc_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int segway_nonlinear_mpc_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
